apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: selogerproxy-digital-nonprod-rw
  namespace: infra-datadog
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
