apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: selogerproxy
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: selogerproxy-digital-nonprod-rw
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: arn:aws:iam::220766614489:role/digital-nonprod-accessselogerproxy-iam-role
