apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: selogerproxy-digital-nonprod-rw-binding
  namespace: app-one
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: selogerproxy-digital-nonprod-rw
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: selogerproxy-digital-nonprod-rw
